:example: example-03-gradle
:groovy: {example}/src/main/groovy

== Migrating to Gradle

As your prototype starts to evolve into a more serious application, you will want to start using a serious build tool like Gradle.
We'll start by creating our `build.gradle` file.

[source, gradle]
.{example}/{example}.gradle
----
include::../{example}/{example}.gradle[]
----
<1> Make use of the incubating `plugins` DSL feature
<2> Tell Gradle to use the Ratpack Groovy Gradle plugin
<3> Tell Gradle to look for artifacts in Bintray JCenter

We'll also move our `ratpack.groovy` file to `$projectDir/src/ratpack/ratpack.groovy` and put `CORSHandler.groovy` in the typical `$projectDir/src/main/groovy` location for regular Groovy classes.
The `$projectDir/src/ratpack` directory is a convention used by Ratpack as a common directory for holding configuration files, templates, static assets and your main Ratpack application script.

Once everything is in its place you should see a directory structure similar to this:

[source, bash]
.Directory structure after migrating to Gradle
----
example-03-gradle
│   example-03-gradle.gradle
│
└───src
    ├───main
    │   └───groovy
    │           CORSHandler.groovy
    │
    └───ratpack
            ratpack.groovy
----

=== Why not Maven?

Because Ratpack is simply a set of Java libraries, all that is required to build Ratpack applications are the Ratpack jar files and `javac`.
You are free to use any build tool: Ant + Ivy, Maven, Gradle, etc.

Ratpack has first-class Gradle support provided via https://plugins.gradle.org/search?term=ratpack[Ratpack's Gradle plugin].
It allows for easy dependency management (keeps versions of modules in sync) and hooks into https://docs.gradle.org/current/userguide/continuous_build.html[Gradle's continuous functionality].

Can you create a Maven `pom.xml` file from memory?
I certainly cannot.
I can create a `build.gradle` file from memory though.

.build.gradle
[source,gradle]
----
plugins { // <1>
  id 'io.ratpack.ratpack-groovy' version '1.3.3' // <2>
}

repositories {
  jcenter() // <3>
}
----
<1> Make use of Gradle's https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block[incubating Plugins DSL] (since Gradle 2.1)
<2> Declare and apply Ratpack's Gradle plugin for Groovy, provides `ratpack-core` module
<3> Tell Gradle to pull dependencies from Bintray JCenter

Gradle has a number of out of the box features that make it superior to Maven however the one I will highlight here is the Gradle Wrapper.

The Gradle Wrapper is a set of files that enables developer on a project to use the same exact version of Gradle.
This is a best practice when it comes to working with Gradle.
Because Gradle is such a well maintained build tool, there are many updates.
The Gradle Wrapper goes a long way towards preventing "works on my machine" syndrome.
Wrapper scripts are available in `bash` and `bat` formats.
Because the scripts are typically a part of the project, you don't _need_ to install Gradle to use it, just use the `gradlew` scripts.
At some point however, someone somewhere needs to install gradle.
I recommend installing http://sdkman.io to manage Gradle installations.
To generate the wrapper, invoke `gradle wrapper` from the command line.

[NOTE]
When generating scripts from Windows, make sure to `chmod +x gradlew` so that your *nix/Mac co-workers and CI server can execute the wrapper script.

=== Launching via Gradle

Launching our Ratpack application is straightforward thanks to the Ratpack Gradle plugin.

Simply execute the `:run` task to launch your Ratpack application:

[source, bash, subs="attributes"]
----
$ ./gradlew :{example}:run

$ curl -s localhost:5050
Hej Verden
----

=== Continuous Mode

If you add `-t` or `--continuous` to the task execution, Gradle's continuous mode will be invoked.
Gradle's continuous mode monitors source code and reruns the specified task.

[TIP]
Continuous mode cannot currently respond to changes in Gradle build scripts, only in source code or resources.

[source, bash, subs="attributes"]
----
$ ./gradlew :{example}:run -t

$ curl -s localhost:5050 | cat
Hej Verden!

# modify ratpack.groovy

Change detected, executing build...

:{example}:compileJava UP-TO-DATE
:{example}:compileGroovy UP-TO-DATE
:{example}:processResources
:{example}:classes
:{example}:configureRun
:{example}:run
Ratpack started (development) for http://localhost:5050

BUILD SUCCESSFUL

Total time: 0.374 secs

$ curl -s localhost:5050
Hej GR8Conf EU 2016!
----

